{{- range $service := .Values.instanceConfig}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    helm.sh/chart: {{ $.Chart.Name }}_{{ $.Chart.Version }}
    app.kubernetes.io/name: {{ $service.app }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- if $.Chart.AppVersion }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  name: {{ $service.app }}-deployment
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $service.app }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  replicas: {{ $service.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $service.app }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      containers:
      - name: {{ $service.app }}-container
        {{- if eq $service.app "id-web" }}
        image: "{{ $.Values.image.repo }}/boldbi-identity:{{ $.Values.image.tag }}"
        {{- else if eq $service.app "id-api" }}
        image: "{{ $.Values.image.repo }}/boldbi-identity-api:{{ $.Values.image.tag }}"
        {{- else if eq $service.app "id-ums" }}
        image: "{{ $.Values.image.repo }}/boldbi-ums:{{ $.Values.image.tag }}"
        {{- else if eq $service.app "bi-web" }}
        image: "{{ $.Values.image.repo }}/boldbi-server:{{ $.Values.image.tag }}"
        {{- else if eq $service.app "bi-api" }}
        image: "{{ $.Values.image.repo }}/boldbi-server-api:{{ $.Values.image.tag }}"
        {{- else if eq $service.app "bi-jobs" }}
        image: "{{ $.Values.image.repo }}/boldbi-server-jobs:{{ $.Values.image.tag }}"
        {{- else if eq $service.app "bi-dataservice" }}
        image: "{{ $.Values.image.repo }}/boldbi-designer:{{ $.Values.image.tag }}"
        {{- end }}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: {{ $service.cpuResourceRequests }}
            memory: {{ $service.memoryResourceRequests }}
        {{- if eq $service.app "id-web" }}
        env:
        - name: APP_BASE_URL
          value: {{ $.Values.appBaseUrl }}
        {{- if $.Values.optionalLibs }}
        - name: INSTALL_OPTIONAL_LIBS
          value: {{ $.Values.optionalLibs }}
        {{- end }}
        {{- else if and (eq $service.app "bi-dataservice") $.Values.bingMapWidget.enabled }}
        env:
        - name: widget_bing_map_enable
          value: "{{ $.Values.bingMapWidget.enabled }}"
        - name: widget_bing_map_api_key
          value: "{{ $.Values.bingMapWidget.apiKey }}"
        {{- end }}
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          {{- if eq $service.app "id-web" }}
          initialDelaySeconds: 30
          {{- else }}
          initialDelaySeconds: 20
          {{- end }}
          periodSeconds: 10
        volumeMounts:
        - mountPath: /boldbi/app_data
          name: {{ $service.app }}-volume
        {{- if eq $service.app "id-web" }}
        - mountPath: /boldbi/idp/web/logs
        {{- else if eq $service.app "id-api" }}
        - mountPath: /boldbi/idp/api/logs
        {{- else if eq $service.app "id-ums" }}
        - mountPath: /boldbi/idp/ums/logs
        {{- else if eq $service.app "bi-web" }}
        - mountPath: /boldbi/bi/web/logs
        {{- else if eq $service.app "bi-api" }}
        - mountPath: /boldbi/bi/api/logs
        {{- else if eq $service.app "bi-jobs" }}
        - mountPath: /boldbi/bi/jobs/logs
        {{- else if eq $service.app "bi-dataservice" }}
        - mountPath: /boldbi/bi/dataservice/logs
        {{- end }}
          name: log4net-config-volume
      volumes:
      - name: {{ $service.app }}-volume
        persistentVolumeClaim:
          claimName: boldbi-fileserver-claim
          readOnly: false
      - name: log4net-config-volume
        configMap:
          name: log4net-config
---
{{- end }}