{{- if .Values.autoscaling.enabled }}
{{- range $service := .Values.services}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $service.hpaName }}
  labels:
    helm.sh/chart: {{ $.Chart.Name }}_{{ $.Chart.Version }}
    app.kubernetes.io/name: {{ $service.app }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- if $.Chart.AppVersion }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  namespace: {{ $.Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $service.deploymentName }}
  minReplicas: {{ $service.minReplicas }}
  maxReplicas: {{ $service.maxReplicas }}
  metrics:
  {{- if $.Values.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $.Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if $.Values.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ $.Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if ne $.Values.clusterType "gke" }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ $.Values.autoscaling.behavior.stabilizationWindowSeconds }}
      policies:
      - type: Pods
        value: {{ $.Values.autoscaling.behavior.podsValue }}
        periodSeconds: {{ $.Values.autoscaling.behavior.podsPeriodSeconds }}
      - type: Percent
        value: {{ $.Values.autoscaling.behavior.percentValue }}
        periodSeconds: {{ $.Values.autoscaling.behavior.percentPeriodSeconds }}
  {{- end }}
---
{{- end }}
{{- end }}