{{- range $service := .Values.services}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.serviceName }}
  namespace: {{ $.Values.namespace }}
  labels:
    helm.sh/chart: {{ $.Chart.Name }}_{{ $.Chart.Version }}
    app.kubernetes.io/name: {{ $service.app }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- if $.Chart.AppVersion }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  type: {{ $.Values.service.type }}
  ports:
  - name: {{ $service.portName }}
    port: {{ $service.port }}
    targetPort: {{ $.Values.service.targetPort }}
    protocol: {{ $.Values.service.protocol }}
  selector:
    app.kubernetes.io/name: {{ $service.app }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
---
{{- end }}