# Default values for boldbi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: boldbi
appBaseUrl: ""
optionalLibs: ""
clusterProvider: ""

persistentVolume:
  # persistent volumes were global resources. 
  # so if you already have Bold BI installed in your cluster, then the previous persistent volume name will conflict with current installation.
  # Change this name to avoid conflicts with previous Bold BI persistent volumes.
  name: "boldbi-fileserver"
  capacity: 3Gi
  gke:
    fileShareName: ""
    fileShareIp: ""
  eks:
    efsFileSystemId: ""
  aks:
    fileShareName: ""
    # base64 string
    azureStorageAccountName: ""
    # base64 string
    azureStorageAccountKey: ""
  onpremise:
    hostPath: ""
    
image:
  repo: "gcr.io/boldbi-294612"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "4.1.45_20210622"
  pullPolicy: IfNotPresent
imagePullSecrets: []

instanceConfig:
  - app: id-web
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: id-api
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: id-ums
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: bi-web
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: bi-api
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: bi-jobs
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
  - app: bi-dataservice
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 20
    cpuResourceRequests: 250m
    memoryResourceRequests: 750Mi
   
service:
  type: ClusterIP
  port: 80
   
autoscaling:
  enabled: true
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  behavior:
    stabilizationWindowSeconds: 60
    podsValue: 1
    podsPeriodSeconds: 60
    percentValue: 10
    percentPeriodSeconds: 60
  
bingMapWidget:
  enabled: false
  apiKey: ""
  
ingress:
  enabled: true
  secretName: boldbi-tls
  # tls:
    # enabled: false
    # hostArray:
      # - hosts: 
          # - kubernetes.docker.internal
          # - example.com
        # secretName: boldbi-tls